CC=gcc
CFLAGS=-O2 `sdl2-config --cflags`
LINK=-O2 `sdl2-config --libs` -lSDL2_image
SRC=game.c sdl_driver.c main.c
OBJ=$(SRC:.c=.o)

%.o:	%.c
	$(CC) -c $(CFLAGS) $< 

game: 	$(OBJ)
	$(CC) $(LINK) $(OBJ) -o $@

clean:
	rm *.o game
